"""phone otp login, google login

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-29 16:23:08.666775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone_number'), 'otp_codes', ['phone_number'], unique=True)
    op.add_column('users', sa.Column('google_sub', sa.String(length=64), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # Autogenerate doesn't diff CHECK constraint bodies by text (only
    # presence/absence by name), so the relaxed "NULL is allowed" version
    # of this constraint (db/models/user.py) has to be swapped in by hand:
    # phone_number just became nullable above, and the old constraint body
    # would reject every NULL phone_number row outright.
    op.drop_constraint(op.f('ck_users_phone_number_min_length'), 'users', type_='check')
    op.create_check_constraint(
        'phone_number_min_length', 'users', 'phone_number IS NULL OR length(phone_number) >= 8'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_phone_number_min_length'), 'users', type_='check')
    op.create_check_constraint(
        'phone_number_min_length', 'users', 'length(phone_number) >= 8'
    )
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'google_sub')
    op.drop_index(op.f('ix_otp_codes_phone_number'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
