"""user profile fields: gender, dob, tob, pob

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-30 05:56:38.106615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='gender', native_enum=False, length=20), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('time_of_birth', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('place_of_birth', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'place_of_birth')
    op.drop_column('users', 'time_of_birth')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
