"""drop astrology fields from user profile, add avatar_url and timezone

Revision ID: 0005
Revises: 0004
Create Date: 2026-06-30 06:07:27.582550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.drop_column('users', 'gender')
    op.drop_column('users', 'place_of_birth')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'time_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_of_birth', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('place_of_birth', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
