// frontend/src/pages/TermsOfUse.jsx
//
// See PrivacyPolicy.jsx's header comment for the bracketed-placeholder and
// English-first rationale — same applies here.
import { Link } from 'react-router-dom'
import Seo from '../components/Seo'
import StaticPageLayout from '../components/StaticPageLayout'

const h2 = 'font-serif font-semibold text-lg text-ink mt-7 mb-2 scroll-mt-20'
const ul = 'list-disc pl-5 space-y-1.5'

export default function TermsOfUse() {
  return (
    <>
      <Seo
        title="Terms of Use"
        description="The terms governing your use of Star Jyotish — eligibility, the nature of AI-generated astrology content, payments, liability, and your rights as a user."
        path="/terms"
      />
      <StaticPageLayout title="Terms of Use" maxWidth="max-w-3xl">
        <p className="text-ink-faint text-xs">Last updated: 29 June 2026</p>

        <p>
          These Terms of Use ("Terms") govern your access to and use of starjyotish.com and related services
          (the "Platform"), operated by Star Jyotish ("we", "us", "our"). By using the Platform, you agree to
          these Terms. Please also read our <Link to="/disclaimer" className="text-primary-dark hover:underline">Astrology
          Disclaimer</Link>, <Link to="/privacy" className="text-primary-dark hover:underline">Privacy Policy</Link>, and{' '}
          <Link to="/refund-policy" className="text-primary-dark hover:underline">Refund & Cancellation Policy</Link>,
          which form part of these Terms by reference.
        </p>
        <p className="bg-primary-light border border-primary/30 rounded-xl px-4 py-3 text-ink text-xs leading-relaxed">
          📝 Published in English; the English text governs in case of any conflict with a future Hindi version.
        </p>

        <h2 className={h2}>1. Eligibility</h2>
        <p>You must be at least 18 years old to create an account or make a purchase on the Platform. If you are
          generating a birth chart for a child, you confirm you are doing so as that child's parent or legal
          guardian. The free Kundli and reading tools may be used by anyone browsing the Platform, subject to
          these Terms.</p>

        <h2 className={h2}>2. The nature of this service — please read carefully</h2>
        <p>Star Jyotish provides Vedic astrology calculations (charts, Dasha periods, divisional charts, and
          similar) and AI-generated interpretations of those calculations. This is offered for guidance,
          self-reflection, and entertainment. <strong className="text-ink">It is not professional medical, legal,
          financial, or psychological advice, and no outcome, prediction, or remedy is guaranteed.</strong> You
          are solely responsible for any decisions you make based on content from the Platform, and we strongly
          recommend consulting a qualified professional before making significant medical, legal, or financial
          decisions. See our full <Link to="/disclaimer" className="text-primary-dark hover:underline">Disclaimer</Link>.</p>

        <h2 className={h2}>3. AI-generated content</h2>
        <p>Readings, "Ask the Chart" answers, and topic reports (career, relationship, health, finance) are
          generated by AI language models grounded in our astrology reference library. While we ground these
          outputs in structured astrological material to keep them consistent with the methodology shown, AI
          systems can occasionally produce inaccurate, incomplete, or inconsistent output. We do not warrant the
          accuracy of any specific AI-generated statement.</p>

        <h2 className={h2}>4. Your account (once account features launch)</h2>
        <p>When account registration becomes available, you'll be responsible for keeping your login credentials
          confidential and for all activity under your account. Notify us immediately at the contact below if you
          suspect unauthorized access.</p>

        <h2 className={h2}>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className={ul}>
          <li>Use automated means (bots, scrapers) to access the Platform or circumvent rate limits</li>
          <li>Attempt to extract, reverse-engineer, or systematically harvest our astrology reference library or
            AI prompts</li>
          <li>Use the Platform for any unlawful purpose, or to harass, defame, or harm another person</li>
          <li>Impersonate another person when entering birth details, with intent to deceive or cause harm</li>
          <li>Interfere with the Platform's security, availability, or normal operation</li>
        </ul>
        <p>We may suspend or terminate access for anyone who violates this section.</p>

        <h2 className={h2}>6. Intellectual property</h2>
        <p>The Platform's design, branding, chart-rendering technology, and our astrology reference library are
          owned by Star Jyotish and protected by applicable intellectual property law. You may not copy,
          reproduce, or create derivative works from these except for your own personal, non-commercial use of
          the reports you generate. You retain ownership of the birth details and questions you submit; by
          submitting them, you grant us a license to process them solely to provide you the requested chart,
          reading, or report (see our <Link to="/privacy" className="text-primary-dark hover:underline">Privacy
          Policy</Link> for how that data is handled).</p>

        <h2 className={h2}>7. Fees & payments</h2>
        <p>Some reports and features may require payment, at prices displayed to you at the time of purchase,
          inclusive of any applicable taxes (e.g. GST) unless stated otherwise. Payments will be processed by a
          licensed third-party payment gateway; we do not store your full payment card details. Refunds and
          cancellations are governed by our <Link to="/refund-policy" className="text-primary-dark hover:underline">Refund
          & Cancellation Policy</Link>.</p>

        <h2 className={h2}>8. Third-party services</h2>
        <p>The Platform relies on third-party services (AI providers, geocoding, hosting, and — once live —
          payments) described in our Privacy Policy. We are not responsible for the availability, content, or
          practices of these third parties beyond our agreements with them.</p>

        <h2 className={h2}>9. Disclaimer of warranties</h2>
        <p>The Platform is provided "as is" and "as available," without warranties of any kind, express or
          implied, including fitness for a particular purpose or non-infringement. We do not warrant that the
          Platform will be uninterrupted, error-free, or available at all times.</p>

        <h2 className={h2}>10. Limitation of liability</h2>
        <p>To the maximum extent permitted by Indian law, Star Jyotish shall not be liable for any indirect,
          incidental, special, or consequential damages arising from your use of the Platform, including
          decisions made in reliance on astrological content. Where liability cannot be excluded, our total
          liability to you for any claim is limited to the amount you paid us for the specific service giving
          rise to the claim in the preceding three months, or ₹1,000, whichever is higher. Nothing in these
          Terms limits liability that cannot lawfully be limited, such as liability for fraud or gross
          negligence.</p>

        <h2 className={h2}>11. Indemnification</h2>
        <p>You agree to indemnify and hold Star Jyotish harmless from claims, losses, or expenses (including
          reasonable legal fees) arising from your violation of these Terms or misuse of the Platform.</p>

        <h2 className={h2}>12. Termination</h2>
        <p>We may suspend or terminate your access to the Platform at any time for violation of these Terms, or
          to comply with legal obligations. You may stop using the Platform at any time; once accounts exist,
          you'll be able to request account deletion as described in our Privacy Policy.</p>

        <h2 className={h2}>13. Governing law & jurisdiction</h2>
        <p>These Terms are governed by the laws of India. Subject to applicable consumer-protection law, courts
          at <em className="text-ink-faint">Raigarh, Chhattisgarh, India [to be updated to match the company's
          registered office once incorporated]</em> shall have exclusive jurisdiction over any dispute arising
          from these Terms.</p>

        <h2 className={h2}>14. Changes to these Terms</h2>
        <p>We may update these Terms from time to time; continued use of the Platform after an update
          constitutes acceptance of the revised Terms. We'll update the "Last updated" date above whenever we do.</p>

        <h2 className={h2}>15. Contact</h2>
        <p>Questions about these Terms can be sent to{' '}
          <a href="mailto:contact@starjyotish.com" className="text-primary-dark hover:underline">contact@starjyotish.com</a>.</p>
      </StaticPageLayout>
    </>
  )
}
